version: "3.1"
services:
  mysql_cursos:
    container_name: mysql_cursos
    hostname: mysql_cursos
    image: mysql
    restart: always
    command: 
      - --default-authentication-plugin=mysql_native_passwodrd
      - --character-set-server=utf8mb4
      - --colation-server=utf8mb4_unicode_ci
    volumes:
      - \MySQLDBData\mysqlonly\mysql_cursos
    ports:
      - 3308:3308
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: base_de_dados
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha